# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Johannes\Documents\Python\Sudoku\UIs\Sudoku2.ui'
#
# Created: Sun Sep 22 12:55:15 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sudokusolver(object):
    def setupUi(self, Sudokusolver):
        Sudokusolver.setObjectName(_fromUtf8("Sudokusolver"))
        Sudokusolver.resize(401, 432)
        self.layoutWidget = QtGui.QWidget(Sudokusolver)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 158, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget_2 = QtGui.QWidget(Sudokusolver)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 50, 353, 353))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.le12 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le12.setMinimumSize(QtCore.QSize(31, 31))
        self.le12.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le12.setFont(font)
        self.le12.setText(_fromUtf8(""))
        self.le12.setObjectName(_fromUtf8("le12"))
        self.gridLayout.addWidget(self.le12, 1, 2, 1, 1)
        self.le10 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le10.setMinimumSize(QtCore.QSize(31, 31))
        self.le10.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le10.setFont(font)
        self.le10.setText(_fromUtf8(""))
        self.le10.setObjectName(_fromUtf8("le10"))
        self.gridLayout.addWidget(self.le10, 1, 0, 1, 1)
        self.le1 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le1.setMinimumSize(QtCore.QSize(31, 31))
        self.le1.setMaximumSize(QtCore.QSize(31, 31))
        self.le1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le1.setFont(font)
        self.le1.setText(_fromUtf8(""))
        self.le1.setObjectName(_fromUtf8("le1"))
        self.gridLayout.addWidget(self.le1, 0, 0, 1, 1)
        self.le3 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le3.setMinimumSize(QtCore.QSize(31, 31))
        self.le3.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le3.setFont(font)
        self.le3.setText(_fromUtf8(""))
        self.le3.setObjectName(_fromUtf8("le3"))
        self.gridLayout.addWidget(self.le3, 0, 2, 1, 1)
        self.le2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le2.setMinimumSize(QtCore.QSize(31, 31))
        self.le2.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le2.setFont(font)
        self.le2.setText(_fromUtf8(""))
        self.le2.setObjectName(_fromUtf8("le2"))
        self.gridLayout.addWidget(self.le2, 0, 1, 1, 1)
        self.le19 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le19.setMinimumSize(QtCore.QSize(31, 31))
        self.le19.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le19.setFont(font)
        self.le19.setText(_fromUtf8(""))
        self.le19.setObjectName(_fromUtf8("le19"))
        self.gridLayout.addWidget(self.le19, 2, 0, 1, 1)
        self.le20 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le20.setMinimumSize(QtCore.QSize(31, 31))
        self.le20.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le20.setFont(font)
        self.le20.setText(_fromUtf8(""))
        self.le20.setObjectName(_fromUtf8("le20"))
        self.gridLayout.addWidget(self.le20, 2, 1, 1, 1)
        self.le11 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le11.setMinimumSize(QtCore.QSize(31, 31))
        self.le11.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le11.setFont(font)
        self.le11.setText(_fromUtf8(""))
        self.le11.setObjectName(_fromUtf8("le11"))
        self.gridLayout.addWidget(self.le11, 1, 1, 1, 1)
        self.le21 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le21.setMinimumSize(QtCore.QSize(31, 31))
        self.le21.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le21.setFont(font)
        self.le21.setText(_fromUtf8(""))
        self.le21.setObjectName(_fromUtf8("le21"))
        self.gridLayout.addWidget(self.le21, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.le4 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le4.setMinimumSize(QtCore.QSize(31, 31))
        self.le4.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le4.setFont(font)
        self.le4.setText(_fromUtf8(""))
        self.le4.setObjectName(_fromUtf8("le4"))
        self.gridLayout_2.addWidget(self.le4, 0, 0, 1, 1)
        self.le5 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le5.setMinimumSize(QtCore.QSize(31, 31))
        self.le5.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le5.setFont(font)
        self.le5.setText(_fromUtf8(""))
        self.le5.setObjectName(_fromUtf8("le5"))
        self.gridLayout_2.addWidget(self.le5, 0, 1, 1, 1)
        self.le6 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le6.setMinimumSize(QtCore.QSize(31, 31))
        self.le6.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le6.setFont(font)
        self.le6.setText(_fromUtf8(""))
        self.le6.setObjectName(_fromUtf8("le6"))
        self.gridLayout_2.addWidget(self.le6, 0, 2, 1, 1)
        self.le13 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le13.setMinimumSize(QtCore.QSize(31, 31))
        self.le13.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le13.setFont(font)
        self.le13.setText(_fromUtf8(""))
        self.le13.setObjectName(_fromUtf8("le13"))
        self.gridLayout_2.addWidget(self.le13, 1, 0, 1, 1)
        self.le14 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le14.setMinimumSize(QtCore.QSize(31, 31))
        self.le14.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le14.setFont(font)
        self.le14.setText(_fromUtf8(""))
        self.le14.setObjectName(_fromUtf8("le14"))
        self.gridLayout_2.addWidget(self.le14, 1, 1, 1, 1)
        self.le15 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le15.setMinimumSize(QtCore.QSize(31, 31))
        self.le15.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le15.setFont(font)
        self.le15.setText(_fromUtf8(""))
        self.le15.setObjectName(_fromUtf8("le15"))
        self.gridLayout_2.addWidget(self.le15, 1, 2, 1, 1)
        self.le22 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le22.setMinimumSize(QtCore.QSize(31, 31))
        self.le22.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le22.setFont(font)
        self.le22.setText(_fromUtf8(""))
        self.le22.setObjectName(_fromUtf8("le22"))
        self.gridLayout_2.addWidget(self.le22, 2, 0, 1, 1)
        self.le23 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le23.setMinimumSize(QtCore.QSize(31, 31))
        self.le23.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le23.setFont(font)
        self.le23.setText(_fromUtf8(""))
        self.le23.setObjectName(_fromUtf8("le23"))
        self.gridLayout_2.addWidget(self.le23, 2, 1, 1, 1)
        self.le24 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le24.setMinimumSize(QtCore.QSize(31, 31))
        self.le24.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le24.setFont(font)
        self.le24.setText(_fromUtf8(""))
        self.le24.setObjectName(_fromUtf8("le24"))
        self.gridLayout_2.addWidget(self.le24, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.le7 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le7.setMinimumSize(QtCore.QSize(31, 31))
        self.le7.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le7.setFont(font)
        self.le7.setText(_fromUtf8(""))
        self.le7.setObjectName(_fromUtf8("le7"))
        self.gridLayout_3.addWidget(self.le7, 0, 0, 1, 1)
        self.le8 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le8.setMinimumSize(QtCore.QSize(31, 31))
        self.le8.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le8.setFont(font)
        self.le8.setText(_fromUtf8(""))
        self.le8.setObjectName(_fromUtf8("le8"))
        self.gridLayout_3.addWidget(self.le8, 0, 1, 1, 1)
        self.le9 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le9.setMinimumSize(QtCore.QSize(31, 31))
        self.le9.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le9.setFont(font)
        self.le9.setText(_fromUtf8(""))
        self.le9.setObjectName(_fromUtf8("le9"))
        self.gridLayout_3.addWidget(self.le9, 0, 2, 1, 1)
        self.le16 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le16.setMinimumSize(QtCore.QSize(31, 31))
        self.le16.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le16.setFont(font)
        self.le16.setText(_fromUtf8(""))
        self.le16.setObjectName(_fromUtf8("le16"))
        self.gridLayout_3.addWidget(self.le16, 1, 0, 1, 1)
        self.le17 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le17.setMinimumSize(QtCore.QSize(31, 31))
        self.le17.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le17.setFont(font)
        self.le17.setText(_fromUtf8(""))
        self.le17.setObjectName(_fromUtf8("le17"))
        self.gridLayout_3.addWidget(self.le17, 1, 1, 1, 1)
        self.le18 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le18.setMinimumSize(QtCore.QSize(31, 31))
        self.le18.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le18.setFont(font)
        self.le18.setText(_fromUtf8(""))
        self.le18.setObjectName(_fromUtf8("le18"))
        self.gridLayout_3.addWidget(self.le18, 1, 2, 1, 1)
        self.le25 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le25.setMinimumSize(QtCore.QSize(31, 31))
        self.le25.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le25.setFont(font)
        self.le25.setText(_fromUtf8(""))
        self.le25.setObjectName(_fromUtf8("le25"))
        self.gridLayout_3.addWidget(self.le25, 2, 0, 1, 1)
        self.le26 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le26.setMinimumSize(QtCore.QSize(31, 31))
        self.le26.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le26.setFont(font)
        self.le26.setText(_fromUtf8(""))
        self.le26.setObjectName(_fromUtf8("le26"))
        self.gridLayout_3.addWidget(self.le26, 2, 1, 1, 1)
        self.le27 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le27.setMinimumSize(QtCore.QSize(31, 31))
        self.le27.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le27.setFont(font)
        self.le27.setText(_fromUtf8(""))
        self.le27.setObjectName(_fromUtf8("le27"))
        self.gridLayout_3.addWidget(self.le27, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 4, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.le58 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le58.setMinimumSize(QtCore.QSize(31, 31))
        self.le58.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le58.setFont(font)
        self.le58.setText(_fromUtf8(""))
        self.le58.setObjectName(_fromUtf8("le58"))
        self.gridLayout_8.addWidget(self.le58, 0, 0, 1, 1)
        self.le59 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le59.setMinimumSize(QtCore.QSize(31, 31))
        self.le59.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le59.setFont(font)
        self.le59.setText(_fromUtf8(""))
        self.le59.setObjectName(_fromUtf8("le59"))
        self.gridLayout_8.addWidget(self.le59, 0, 1, 1, 1)
        self.le60 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le60.setMinimumSize(QtCore.QSize(31, 31))
        self.le60.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le60.setFont(font)
        self.le60.setText(_fromUtf8(""))
        self.le60.setObjectName(_fromUtf8("le60"))
        self.gridLayout_8.addWidget(self.le60, 0, 2, 1, 1)
        self.le67 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le67.setMinimumSize(QtCore.QSize(31, 31))
        self.le67.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le67.setFont(font)
        self.le67.setText(_fromUtf8(""))
        self.le67.setObjectName(_fromUtf8("le67"))
        self.gridLayout_8.addWidget(self.le67, 1, 0, 1, 1)
        self.le68 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le68.setMinimumSize(QtCore.QSize(31, 31))
        self.le68.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le68.setFont(font)
        self.le68.setText(_fromUtf8(""))
        self.le68.setObjectName(_fromUtf8("le68"))
        self.gridLayout_8.addWidget(self.le68, 1, 1, 1, 1)
        self.le69 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le69.setMinimumSize(QtCore.QSize(31, 31))
        self.le69.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le69.setFont(font)
        self.le69.setText(_fromUtf8(""))
        self.le69.setObjectName(_fromUtf8("le69"))
        self.gridLayout_8.addWidget(self.le69, 1, 2, 1, 1)
        self.le76 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le76.setMinimumSize(QtCore.QSize(31, 31))
        self.le76.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le76.setFont(font)
        self.le76.setText(_fromUtf8(""))
        self.le76.setObjectName(_fromUtf8("le76"))
        self.gridLayout_8.addWidget(self.le76, 2, 0, 1, 1)
        self.le77 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le77.setMinimumSize(QtCore.QSize(31, 31))
        self.le77.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le77.setFont(font)
        self.le77.setText(_fromUtf8(""))
        self.le77.setObjectName(_fromUtf8("le77"))
        self.gridLayout_8.addWidget(self.le77, 2, 1, 1, 1)
        self.le78 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le78.setMinimumSize(QtCore.QSize(31, 31))
        self.le78.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le78.setFont(font)
        self.le78.setText(_fromUtf8(""))
        self.le78.setObjectName(_fromUtf8("le78"))
        self.gridLayout_8.addWidget(self.le78, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 4, 2, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.le28 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le28.setMinimumSize(QtCore.QSize(31, 31))
        self.le28.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le28.setFont(font)
        self.le28.setText(_fromUtf8(""))
        self.le28.setObjectName(_fromUtf8("le28"))
        self.gridLayout_6.addWidget(self.le28, 0, 0, 1, 1)
        self.le29 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le29.setMinimumSize(QtCore.QSize(31, 31))
        self.le29.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le29.setFont(font)
        self.le29.setText(_fromUtf8(""))
        self.le29.setObjectName(_fromUtf8("le29"))
        self.gridLayout_6.addWidget(self.le29, 0, 1, 1, 1)
        self.le30 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le30.setMinimumSize(QtCore.QSize(31, 31))
        self.le30.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le30.setFont(font)
        self.le30.setText(_fromUtf8(""))
        self.le30.setObjectName(_fromUtf8("le30"))
        self.gridLayout_6.addWidget(self.le30, 0, 2, 1, 1)
        self.le37 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le37.setMinimumSize(QtCore.QSize(31, 31))
        self.le37.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le37.setFont(font)
        self.le37.setText(_fromUtf8(""))
        self.le37.setObjectName(_fromUtf8("le37"))
        self.gridLayout_6.addWidget(self.le37, 1, 0, 1, 1)
        self.le38 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le38.setMinimumSize(QtCore.QSize(31, 31))
        self.le38.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le38.setFont(font)
        self.le38.setText(_fromUtf8(""))
        self.le38.setObjectName(_fromUtf8("le38"))
        self.gridLayout_6.addWidget(self.le38, 1, 1, 1, 1)
        self.le39 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le39.setMinimumSize(QtCore.QSize(31, 31))
        self.le39.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le39.setFont(font)
        self.le39.setText(_fromUtf8(""))
        self.le39.setObjectName(_fromUtf8("le39"))
        self.gridLayout_6.addWidget(self.le39, 1, 2, 1, 1)
        self.le46 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le46.setMinimumSize(QtCore.QSize(31, 31))
        self.le46.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le46.setFont(font)
        self.le46.setText(_fromUtf8(""))
        self.le46.setObjectName(_fromUtf8("le46"))
        self.gridLayout_6.addWidget(self.le46, 2, 0, 1, 1)
        self.le47 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le47.setMinimumSize(QtCore.QSize(31, 31))
        self.le47.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le47.setFont(font)
        self.le47.setText(_fromUtf8(""))
        self.le47.setObjectName(_fromUtf8("le47"))
        self.gridLayout_6.addWidget(self.le47, 2, 1, 1, 1)
        self.le48 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le48.setMinimumSize(QtCore.QSize(31, 31))
        self.le48.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le48.setFont(font)
        self.le48.setText(_fromUtf8(""))
        self.le48.setObjectName(_fromUtf8("le48"))
        self.gridLayout_6.addWidget(self.le48, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.le34 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le34.setMinimumSize(QtCore.QSize(31, 31))
        self.le34.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le34.setFont(font)
        self.le34.setText(_fromUtf8(""))
        self.le34.setObjectName(_fromUtf8("le34"))
        self.gridLayout_4.addWidget(self.le34, 0, 0, 1, 1)
        self.le35 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le35.setMinimumSize(QtCore.QSize(31, 31))
        self.le35.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le35.setFont(font)
        self.le35.setText(_fromUtf8(""))
        self.le35.setObjectName(_fromUtf8("le35"))
        self.gridLayout_4.addWidget(self.le35, 0, 1, 1, 1)
        self.le36 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le36.setMinimumSize(QtCore.QSize(31, 31))
        self.le36.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le36.setFont(font)
        self.le36.setText(_fromUtf8(""))
        self.le36.setObjectName(_fromUtf8("le36"))
        self.gridLayout_4.addWidget(self.le36, 0, 2, 1, 1)
        self.le43 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le43.setMinimumSize(QtCore.QSize(31, 31))
        self.le43.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le43.setFont(font)
        self.le43.setText(_fromUtf8(""))
        self.le43.setObjectName(_fromUtf8("le43"))
        self.gridLayout_4.addWidget(self.le43, 1, 0, 1, 1)
        self.le44 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le44.setMinimumSize(QtCore.QSize(31, 31))
        self.le44.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le44.setFont(font)
        self.le44.setText(_fromUtf8(""))
        self.le44.setObjectName(_fromUtf8("le44"))
        self.gridLayout_4.addWidget(self.le44, 1, 1, 1, 1)
        self.le45 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le45.setMinimumSize(QtCore.QSize(31, 31))
        self.le45.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le45.setFont(font)
        self.le45.setText(_fromUtf8(""))
        self.le45.setObjectName(_fromUtf8("le45"))
        self.gridLayout_4.addWidget(self.le45, 1, 2, 1, 1)
        self.le52 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le52.setMinimumSize(QtCore.QSize(31, 31))
        self.le52.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le52.setFont(font)
        self.le52.setText(_fromUtf8(""))
        self.le52.setObjectName(_fromUtf8("le52"))
        self.gridLayout_4.addWidget(self.le52, 2, 0, 1, 1)
        self.le53 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le53.setMinimumSize(QtCore.QSize(31, 31))
        self.le53.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le53.setFont(font)
        self.le53.setText(_fromUtf8(""))
        self.le53.setObjectName(_fromUtf8("le53"))
        self.gridLayout_4.addWidget(self.le53, 2, 1, 1, 1)
        self.le54 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le54.setMinimumSize(QtCore.QSize(31, 31))
        self.le54.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le54.setFont(font)
        self.le54.setText(_fromUtf8(""))
        self.le54.setObjectName(_fromUtf8("le54"))
        self.gridLayout_4.addWidget(self.le54, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 2, 4, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.le31 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le31.setMinimumSize(QtCore.QSize(31, 31))
        self.le31.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le31.setFont(font)
        self.le31.setText(_fromUtf8(""))
        self.le31.setObjectName(_fromUtf8("le31"))
        self.gridLayout_5.addWidget(self.le31, 0, 0, 1, 1)
        self.le32 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le32.setMinimumSize(QtCore.QSize(31, 31))
        self.le32.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le32.setFont(font)
        self.le32.setText(_fromUtf8(""))
        self.le32.setObjectName(_fromUtf8("le32"))
        self.gridLayout_5.addWidget(self.le32, 0, 1, 1, 1)
        self.le33 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le33.setMinimumSize(QtCore.QSize(31, 31))
        self.le33.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le33.setFont(font)
        self.le33.setText(_fromUtf8(""))
        self.le33.setObjectName(_fromUtf8("le33"))
        self.gridLayout_5.addWidget(self.le33, 0, 2, 1, 1)
        self.le40 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le40.setMinimumSize(QtCore.QSize(31, 31))
        self.le40.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le40.setFont(font)
        self.le40.setText(_fromUtf8(""))
        self.le40.setObjectName(_fromUtf8("le40"))
        self.gridLayout_5.addWidget(self.le40, 1, 0, 1, 1)
        self.le41 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le41.setMinimumSize(QtCore.QSize(31, 31))
        self.le41.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le41.setFont(font)
        self.le41.setText(_fromUtf8(""))
        self.le41.setObjectName(_fromUtf8("le41"))
        self.gridLayout_5.addWidget(self.le41, 1, 1, 1, 1)
        self.le42 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le42.setMinimumSize(QtCore.QSize(31, 31))
        self.le42.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le42.setFont(font)
        self.le42.setText(_fromUtf8(""))
        self.le42.setObjectName(_fromUtf8("le42"))
        self.gridLayout_5.addWidget(self.le42, 1, 2, 1, 1)
        self.le49 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le49.setMinimumSize(QtCore.QSize(31, 31))
        self.le49.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le49.setFont(font)
        self.le49.setText(_fromUtf8(""))
        self.le49.setObjectName(_fromUtf8("le49"))
        self.gridLayout_5.addWidget(self.le49, 2, 0, 1, 1)
        self.le50 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le50.setMinimumSize(QtCore.QSize(31, 31))
        self.le50.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le50.setFont(font)
        self.le50.setText(_fromUtf8(""))
        self.le50.setObjectName(_fromUtf8("le50"))
        self.gridLayout_5.addWidget(self.le50, 2, 1, 1, 1)
        self.le51 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le51.setMinimumSize(QtCore.QSize(31, 31))
        self.le51.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le51.setFont(font)
        self.le51.setText(_fromUtf8(""))
        self.le51.setObjectName(_fromUtf8("le51"))
        self.gridLayout_5.addWidget(self.le51, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 2, 2, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.le55 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le55.setMinimumSize(QtCore.QSize(31, 31))
        self.le55.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le55.setFont(font)
        self.le55.setText(_fromUtf8(""))
        self.le55.setObjectName(_fromUtf8("le55"))
        self.gridLayout_9.addWidget(self.le55, 0, 0, 1, 1)
        self.le56 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le56.setMinimumSize(QtCore.QSize(31, 31))
        self.le56.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le56.setFont(font)
        self.le56.setText(_fromUtf8(""))
        self.le56.setObjectName(_fromUtf8("le56"))
        self.gridLayout_9.addWidget(self.le56, 0, 1, 1, 1)
        self.le57 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le57.setMinimumSize(QtCore.QSize(31, 31))
        self.le57.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le57.setFont(font)
        self.le57.setText(_fromUtf8(""))
        self.le57.setObjectName(_fromUtf8("le57"))
        self.gridLayout_9.addWidget(self.le57, 0, 2, 1, 1)
        self.le64 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le64.setMinimumSize(QtCore.QSize(31, 31))
        self.le64.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le64.setFont(font)
        self.le64.setText(_fromUtf8(""))
        self.le64.setObjectName(_fromUtf8("le64"))
        self.gridLayout_9.addWidget(self.le64, 1, 0, 1, 1)
        self.le65 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le65.setMinimumSize(QtCore.QSize(31, 31))
        self.le65.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le65.setFont(font)
        self.le65.setText(_fromUtf8(""))
        self.le65.setObjectName(_fromUtf8("le65"))
        self.gridLayout_9.addWidget(self.le65, 1, 1, 1, 1)
        self.le66 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le66.setMinimumSize(QtCore.QSize(31, 31))
        self.le66.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le66.setFont(font)
        self.le66.setText(_fromUtf8(""))
        self.le66.setObjectName(_fromUtf8("le66"))
        self.gridLayout_9.addWidget(self.le66, 1, 2, 1, 1)
        self.le73 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le73.setMinimumSize(QtCore.QSize(31, 31))
        self.le73.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le73.setFont(font)
        self.le73.setText(_fromUtf8(""))
        self.le73.setObjectName(_fromUtf8("le73"))
        self.gridLayout_9.addWidget(self.le73, 2, 0, 1, 1)
        self.le74 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le74.setMinimumSize(QtCore.QSize(31, 31))
        self.le74.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le74.setFont(font)
        self.le74.setText(_fromUtf8(""))
        self.le74.setObjectName(_fromUtf8("le74"))
        self.gridLayout_9.addWidget(self.le74, 2, 1, 1, 1)
        self.le75 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le75.setMinimumSize(QtCore.QSize(31, 31))
        self.le75.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le75.setFont(font)
        self.le75.setText(_fromUtf8(""))
        self.le75.setObjectName(_fromUtf8("le75"))
        self.gridLayout_9.addWidget(self.le75, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 4, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.le61 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le61.setMinimumSize(QtCore.QSize(31, 31))
        self.le61.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le61.setFont(font)
        self.le61.setText(_fromUtf8(""))
        self.le61.setObjectName(_fromUtf8("le61"))
        self.gridLayout_7.addWidget(self.le61, 0, 0, 1, 1)
        self.le62 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le62.setMinimumSize(QtCore.QSize(31, 31))
        self.le62.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le62.setFont(font)
        self.le62.setText(_fromUtf8(""))
        self.le62.setObjectName(_fromUtf8("le62"))
        self.gridLayout_7.addWidget(self.le62, 0, 1, 1, 1)
        self.le63 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le63.setMinimumSize(QtCore.QSize(31, 31))
        self.le63.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le63.setFont(font)
        self.le63.setText(_fromUtf8(""))
        self.le63.setObjectName(_fromUtf8("le63"))
        self.gridLayout_7.addWidget(self.le63, 0, 2, 1, 1)
        self.le70 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le70.setMinimumSize(QtCore.QSize(31, 31))
        self.le70.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le70.setFont(font)
        self.le70.setText(_fromUtf8(""))
        self.le70.setObjectName(_fromUtf8("le70"))
        self.gridLayout_7.addWidget(self.le70, 1, 0, 1, 1)
        self.le71 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le71.setMinimumSize(QtCore.QSize(31, 31))
        self.le71.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le71.setFont(font)
        self.le71.setText(_fromUtf8(""))
        self.le71.setObjectName(_fromUtf8("le71"))
        self.gridLayout_7.addWidget(self.le71, 1, 1, 1, 1)
        self.le72 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le72.setMinimumSize(QtCore.QSize(31, 31))
        self.le72.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le72.setFont(font)
        self.le72.setText(_fromUtf8(""))
        self.le72.setObjectName(_fromUtf8("le72"))
        self.gridLayout_7.addWidget(self.le72, 1, 2, 1, 1)
        self.le79 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le79.setMinimumSize(QtCore.QSize(31, 31))
        self.le79.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le79.setFont(font)
        self.le79.setText(_fromUtf8(""))
        self.le79.setObjectName(_fromUtf8("le79"))
        self.gridLayout_7.addWidget(self.le79, 2, 0, 1, 1)
        self.le80 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le80.setMinimumSize(QtCore.QSize(31, 31))
        self.le80.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le80.setFont(font)
        self.le80.setText(_fromUtf8(""))
        self.le80.setObjectName(_fromUtf8("le80"))
        self.gridLayout_7.addWidget(self.le80, 2, 1, 1, 1)
        self.le81 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le81.setMinimumSize(QtCore.QSize(31, 31))
        self.le81.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le81.setFont(font)
        self.le81.setText(_fromUtf8(""))
        self.le81.setObjectName(_fromUtf8("le81"))
        self.gridLayout_7.addWidget(self.le81, 2, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 4, 4, 1, 1)
        self.line_11 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_11.setFont(font)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_10.addWidget(self.line_11, 1, 4, 1, 1)
        self.line_10 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_10.setFont(font)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_10.addWidget(self.line_10, 1, 2, 1, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_10.addWidget(self.line_5, 4, 1, 1, 1)
        self.line_12 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_12.setFont(font)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_10.addWidget(self.line_12, 0, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_10.addWidget(self.line_4, 2, 3, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_10.addWidget(self.line, 3, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_10.addWidget(self.line_6, 3, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_10.addWidget(self.line_2, 1, 0, 1, 1)
        self.line_8 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_10.addWidget(self.line_8, 4, 3, 1, 1)
        self.line_9 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_9.setFont(font)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_10.addWidget(self.line_9, 2, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_10.addWidget(self.line_7, 3, 4, 1, 1)
        self.line_13 = QtGui.QFrame(self.layoutWidget_2)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_10.addWidget(self.line_13, 0, 3, 1, 1)

        self.retranslateUi(Sudokusolver)
        QtCore.QMetaObject.connectSlotsByName(Sudokusolver)
        Sudokusolver.setTabOrder(self.le1, self.le2)
        Sudokusolver.setTabOrder(self.le2, self.le3)
        Sudokusolver.setTabOrder(self.le3, self.le4)
        Sudokusolver.setTabOrder(self.le4, self.le5)
        Sudokusolver.setTabOrder(self.le5, self.le6)
        Sudokusolver.setTabOrder(self.le6, self.le7)
        Sudokusolver.setTabOrder(self.le7, self.le8)
        Sudokusolver.setTabOrder(self.le8, self.le9)
        Sudokusolver.setTabOrder(self.le9, self.le10)
        Sudokusolver.setTabOrder(self.le10, self.le11)
        Sudokusolver.setTabOrder(self.le11, self.le12)
        Sudokusolver.setTabOrder(self.le12, self.le13)
        Sudokusolver.setTabOrder(self.le13, self.le14)
        Sudokusolver.setTabOrder(self.le14, self.le15)
        Sudokusolver.setTabOrder(self.le15, self.le16)
        Sudokusolver.setTabOrder(self.le16, self.le17)
        Sudokusolver.setTabOrder(self.le17, self.le18)
        Sudokusolver.setTabOrder(self.le18, self.le19)
        Sudokusolver.setTabOrder(self.le19, self.le20)
        Sudokusolver.setTabOrder(self.le20, self.le21)
        Sudokusolver.setTabOrder(self.le21, self.le22)
        Sudokusolver.setTabOrder(self.le22, self.le23)
        Sudokusolver.setTabOrder(self.le23, self.le24)
        Sudokusolver.setTabOrder(self.le24, self.le25)
        Sudokusolver.setTabOrder(self.le25, self.le26)
        Sudokusolver.setTabOrder(self.le26, self.le27)
        Sudokusolver.setTabOrder(self.le27, self.le28)
        Sudokusolver.setTabOrder(self.le28, self.le29)
        Sudokusolver.setTabOrder(self.le29, self.le30)
        Sudokusolver.setTabOrder(self.le30, self.le31)
        Sudokusolver.setTabOrder(self.le31, self.le32)
        Sudokusolver.setTabOrder(self.le32, self.le33)
        Sudokusolver.setTabOrder(self.le33, self.le34)
        Sudokusolver.setTabOrder(self.le34, self.le35)
        Sudokusolver.setTabOrder(self.le35, self.le36)
        Sudokusolver.setTabOrder(self.le36, self.le37)
        Sudokusolver.setTabOrder(self.le37, self.le38)
        Sudokusolver.setTabOrder(self.le38, self.le39)
        Sudokusolver.setTabOrder(self.le39, self.le40)
        Sudokusolver.setTabOrder(self.le40, self.le41)
        Sudokusolver.setTabOrder(self.le41, self.le42)
        Sudokusolver.setTabOrder(self.le42, self.le43)
        Sudokusolver.setTabOrder(self.le43, self.le44)
        Sudokusolver.setTabOrder(self.le44, self.le45)
        Sudokusolver.setTabOrder(self.le45, self.le46)
        Sudokusolver.setTabOrder(self.le46, self.le47)
        Sudokusolver.setTabOrder(self.le47, self.le48)
        Sudokusolver.setTabOrder(self.le48, self.le49)
        Sudokusolver.setTabOrder(self.le49, self.le50)
        Sudokusolver.setTabOrder(self.le50, self.le51)
        Sudokusolver.setTabOrder(self.le51, self.le52)
        Sudokusolver.setTabOrder(self.le52, self.le53)
        Sudokusolver.setTabOrder(self.le53, self.le54)
        Sudokusolver.setTabOrder(self.le54, self.le55)
        Sudokusolver.setTabOrder(self.le55, self.le56)
        Sudokusolver.setTabOrder(self.le56, self.le57)
        Sudokusolver.setTabOrder(self.le57, self.le58)
        Sudokusolver.setTabOrder(self.le58, self.le59)
        Sudokusolver.setTabOrder(self.le59, self.le60)
        Sudokusolver.setTabOrder(self.le60, self.le61)
        Sudokusolver.setTabOrder(self.le61, self.le62)
        Sudokusolver.setTabOrder(self.le62, self.le63)
        Sudokusolver.setTabOrder(self.le63, self.le64)
        Sudokusolver.setTabOrder(self.le64, self.le65)
        Sudokusolver.setTabOrder(self.le65, self.le66)
        Sudokusolver.setTabOrder(self.le66, self.le67)
        Sudokusolver.setTabOrder(self.le67, self.le68)
        Sudokusolver.setTabOrder(self.le68, self.le69)
        Sudokusolver.setTabOrder(self.le69, self.le70)
        Sudokusolver.setTabOrder(self.le70, self.le71)
        Sudokusolver.setTabOrder(self.le71, self.le72)
        Sudokusolver.setTabOrder(self.le72, self.le73)
        Sudokusolver.setTabOrder(self.le73, self.le74)
        Sudokusolver.setTabOrder(self.le74, self.le75)
        Sudokusolver.setTabOrder(self.le75, self.le76)
        Sudokusolver.setTabOrder(self.le76, self.le77)
        Sudokusolver.setTabOrder(self.le77, self.le78)
        Sudokusolver.setTabOrder(self.le78, self.le79)
        Sudokusolver.setTabOrder(self.le79, self.le80)
        Sudokusolver.setTabOrder(self.le80, self.le81)
        Sudokusolver.setTabOrder(self.le81, self.pushButton)
        Sudokusolver.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, Sudokusolver):
        Sudokusolver.setWindowTitle(_translate("Sudokusolver", "Sudokusolver", None))
        self.pushButton.setText(_translate("Sudokusolver", "lösen", None))
        self.pushButton_2.setText(_translate("Sudokusolver", "Neu", None))

